### ISSUE TITLE
RuntimeError: Directory Canon with 21324 entries considered invalid; not read.

### ISSUE THREAD

**Issue by djjudas21** [camerahub/tagger#37]
```
Processing image 31-1-Image0629.jpg
Traceback (most recent call last):
  File "/home/jonathan/.local/bin/tagger", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jonathan/.local/lib/python3.11/site-packages/camerahub_tagger/main.py", line 78, in main
    with pyexiv2.Image(file) as img:
         ^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan/.local/lib/python3.11/site-packages/pyexiv2/core.py", line 15, in __init__
    self.img = exiv2api.Image(filename.encode(encoding))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Directory Canon with 21324 entries considered invalid; not read.
```

**Comment by djjudas21** [comment]
This is still occurring, e.g.

```
Processing image 29-4-Image0560.jpg
Directory Canon with 21324 entries considered invalid; not read.
 when reading 29-4-Image0560.jpg
```

**Comment by djjudas21** [comment]
The maintainer of pyexiv2 is aware of the issue and recommends suppressing logging: https://github.com/LeoHsiao1/pyexiv2/issues/58
