### ISSUE TITLE
RuntimeError: Directory Canon with 21324 entries considered invalid; not read.

### ISSUE THREAD

**Issue by djjudas21** [camerahub/tagger#44]
```
Processing image 21 2009-11 Brandon Hill & Nuneaton/21-1-Image0307.jpg
Traceback (most recent call last):
  File "/home/jonathan/.local/bin/tagger", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jonathan/.local/lib/python3.11/site-packages/camerahub_tagger/main.py", line 82, in main
    with pyexiv2.Image(file) as img:
         ^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan/.local/lib/python3.11/site-packages/pyexiv2/core.py", line 15, in __init__
    self.img = exiv2api.Image(filename.encode(encoding))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Directory Canon with 21324 entries considered invalid; not read.
```

**Comment by djjudas21** [comment]
Duplicate of #37
